## Tf_Idf

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
corpus=["i love nlp",
        "i love mechine learning"]

vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(corpus)

print("Vocabulary:",vectorizer.get_feature_names_out())
print("TF_ID Matrix:\n",x.toarray())

Vocabulary: ['learning' 'love' 'mechine' 'nlp']
TF_ID Matrix:
 [[0.         0.57973867 0.         0.81480247]
 [0.6316672  0.44943642 0.6316672  0.        ]]


In [4]:
cor=["machine learning is a subset of artificial intelligence ",
     "i love mechine learning"]
     
vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(cor)

print("Vocabulary:",vectorizer.get_feature_names_out())
print("TF_ID Matrix:\n",x.toarray())

Vocabulary: ['artificial' 'intelligence' 'is' 'learning' 'love' 'machine' 'mechine'
 'of' 'subset']
TF_ID Matrix:
 [[0.39204401 0.39204401 0.39204401 0.27894255 0.         0.39204401
  0.         0.39204401 0.39204401]
 [0.         0.         0.         0.44943642 0.6316672  0.
  0.6316672  0.         0.        ]]


In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("amazon_reviews.csv")

df.head(5)

,sentiments,cleaned_review,review_score
0,positive,i wish would have gotten one earlier love it a...,5
1,neutral,i ve learned this lesson again open the packag...,1
2,neutral,it is so slow and lags find better option,2
3,neutral,roller ball stopped working within months of m...,1
4,neutral,i like the color and size but it few days out ...,1


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17340 entries, 0 to 17339
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   sentiments      17340 non-null  object
 1   cleaned_review  17337 non-null  object
 2   review_score    17340 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 406.5+ KB


In [9]:
df.isnull().sum()

sentiments        0
cleaned_review    3
review_score      0
dtype: int64

In [10]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17337 entries, 0 to 17339
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   sentiments      17337 non-null  object
 1   cleaned_review  17337 non-null  object
 2   review_score    17337 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 541.8+ KB


In [11]:
df.duplicated().sum()

np.int64(1347)

In [12]:
df=df.drop_duplicates()

In [13]:
df.shape

(15990, 3)

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer()
tf_id=vect.fit_transform(df['cleaned_review'])
print("Vocabulary:",vect.get_feature_names_out())
print("Bow Matrix:\n",tf_id.toarray())

Vocabulary: ['aa' 'aaa' 'aaaaa' ... 'zooming' 'zooms' 'zumba']
Bow Matrix:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Sentiment Analysis

In [15]:
!pip install textblob

   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/625.0 kB ? eta -:--:--
   ------------------------------- ------ 524.3/625.0 kB 986.1 kB/s eta 0:00:01
   ---------------------------------------- 625.0/625.0 kB 737.2 kB/s  0:00:00


In [16]:
from textblob import TextBlob

In [17]:
text="i am a very good student"

In [18]:
analysis=TextBlob(text)
analysis.sentiment.polarity

0.9099999999999999

In [19]:
tex="i am a very bad student"
analysis=TextBlob(tex)
analysis.sentiment.polarity

-0.9099999999999998

In [20]:
te="sun rises in the east"
analysis=TextBlob(te)
analysis.sentiment.polarity

0.0

In [21]:
review="Baahubali: The Beginning  is a groundbreaking Indian epic fantasy directed by S.S. Rajamouli, widely acclaimed for its massive scale, groundbreaking VFX (for Indian cinema), and gripping mythical storytelling"
analysis=TextBlob(review)
analysis.sentiment.polarity

0.125

In [22]:
review="The Raja Saab (2026) is a horror-comedy starring Prabhas that has received largely negative reviews, described as a royal disaster with a weak, disjointed script. While fans may appreciate Prabhas’s enthusiastic performance in a lighter role, critics highlighted poor VFX, boring stretches, and a bloated runtime of over three hours. It is generally considered a letdown with poor execution"
analysis=TextBlob(review)
analysis.sentiment.polarity

-0.26071428571428573

In [23]:
day= "The package will arrive on Tuesday"
analysis=TextBlob(day)
analysis.sentiment.polarity

0.0